baseURL = "http://example.org/"
languageCode = "en-us"
title = "mushmouth.tech"

[[menu.main]]
  name = "blog"
  weight = -110
  identifier = "about"
  url = "/blog/"

[params]
  [[params.accounts]]
    name = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/themushmouth"
  [[params.accounts]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/themushmouth"
  [[params.accounts]]
    name = "FC: xxxx-xxxx-xxxx-xxxx"
    icon = "crosshair"
