baseURL = "http://mushmouth.tech/"
languageCode = "en-us"
title = "mushmouth.tech"

[[menu.main]]
  name = "about"
  weight = -110
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "blog"
  weight = -110
  identifier = "blog"
  url = "/blog/"

[params]
  [[params.accounts]]
    name = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/themushmouth"
  [[params.accounts]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/themushmouth"
  [[params.accounts]]
    name = "Mastodon"
    icon = "message-square"
    url = "https://tiny.tilde.website/@mushmouth"
  [[params.accounts]]
    name = "0123-4567-8901-2345"
    iconpath = "/images/friendcode.svg"
